FROM jboss/wildfly:latest

ARG APP_FILE=target/ROOT.war

# Remove default WildFly deployments
RUN rm -rf /opt/jboss/wildfly/standalone/deployments/*

# Copy your application WAR file to the deployments folder
COPY $APP_FILE /opt/jboss/wildfly/standalone/deployments/ROOT.war

# Optimizations (test only)
RUN sed -i 's/<max-threads count="[0-9]*"/<max-threads count="100"/g' /opt/jboss/wildfly/standalone/configuration/standalone.xml
RUN sed -i 's/<keepalive-time time="[0-9]*"/<keepalive-time time="6000"/g' /opt/jboss/wildfly/standalone/configuration/standalone.xml
RUN sed -i '/<subsystem xmlns="urn:jboss:domain:messaging:.*">/,/<\/subsystem>/ s/<\/subsystem>/<!--&-->/g' /opt/jboss/wildfly/standalone/configuration/standalone.xml
RUN sed -i '/<connector name="https"/,/<\/connector>/ s/<\/connector>/<!--&-->/g' /opt/jboss/wildfly/standalone/configuration/standalone.xml
RUN sed -i 's/<level name="INFO"/<level name="WARN"/g' /opt/jboss/wildfly/standalone/configuration/standalone.xml
RUN sed -i '/<location name="management-console">/,/<\/location>/ s/<\/location>/<!--&-->/g' /opt/jboss/wildfly/standalone/configuration/standalone.xml
RUN sed -i 's/<timer-service .*enabled="true"/<timer-service enabled="false"/g' /opt/jboss/wildfly/standalone/configuration/standalone.xml
RUN sed -i '/<subsystem xmlns="urn:jboss:domain:modcluster:.*">/,/<\/subsystem>/ s/<\/subsystem>/<!--&-->/g' /opt/jboss/wildfly/standalone/configuration/standalone.xml
RUN sed -i '/<security-realm name=".*">/,/<\/security-realm>/ s/<\/security-realm>/<!--&-->/g' /opt/jboss/wildfly/standalone/configuration/standalone.xml

# Expose the ports WildFly runs on (HTTP and management)
EXPOSE 8080 9990
